import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bookmark, Check, ChevronLeft, Lightbulb, RefreshCw, Sparkles, Users } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { generateProjectIdeas } from '../services/ai-service';

type Project = { id: string; title: string; summary: string; problem: string; difficulty: string; duration: string; technologies: string[]; features: string[]; innovationScore: number };
const domains = ['Web Development', 'AI / Machine Learning', 'Data Science', 'Mobile Apps', 'Cybersecurity', 'IoT'];

export default function Generator() {
  const navigate = useNavigate();
  const [step, setStep] = useState(1), [loading, setLoading] = useState(false), [results, setResults] = useState<Project[] | null>(null);
  const [saved, setSaved] = useState<string[]>(() => JSON.parse(localStorage.getItem('savedProjectIds') || '[]'));
  const [form, setForm] = useState({ domain: domains[0], skills: '', duration: '2-3 months', complexity: 'Intermediate', teamSize: '2' });
  const generate = async () => { setLoading(true); setResults(await generateProjectIdeas(form.domain, form.skills, form.duration)); setLoading(false); };
  const save = (id: string) => { const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved(next); localStorage.setItem('savedProjectIds', JSON.stringify(next)); };

  if (results) return <div className="min-h-screen bg-slate-950 p-5 text-slate-100 md:p-10"><div className="mx-auto max-w-6xl">
    <button onClick={() => setResults(null)} className="mb-6 flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ChevronLeft size={17}/> Refine answers</button>
    <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 flex items-center gap-2 text-sm font-medium text-indigo-300"><Sparkles size={16}/> PERSONALIZED FOR YOU</p><h1 className="text-3xl font-bold md:text-4xl">Choose an idea worth building.</h1><p className="mt-2 text-slate-400">Save ideas or open one to begin mentorship.</p></div><Button variant="outline" onClick={generate} disabled={loading}><RefreshCw size={16} className={`mr-2 ${loading ? 'animate-spin' : ''}`}/>New suggestions</Button></div>
    <div className="grid gap-5 lg:grid-cols-3">{results.map(project => { const feasible = Math.min(96, project.innovationScore + (form.complexity === project.difficulty ? 5 : 0)); const isSaved = saved.includes(project.id); return <article key={project.id} className="flex flex-col rounded-2xl border border-slate-800 bg-slate-900/80 p-6 shadow-xl shadow-black/10">
      <div className="mb-5 flex items-start justify-between gap-3"><span className="rounded-full bg-indigo-500/15 px-3 py-1 text-xs font-semibold text-indigo-300">{project.difficulty}</span><button aria-label="Save project" onClick={() => save(project.id)} className={isSaved ? 'text-amber-300' : 'text-slate-500 hover:text-amber-300'}><Bookmark size={20} fill={isSaved ? 'currentColor' : 'none'}/></button></div>
      <h2 className="text-xl font-bold text-white">{project.title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-400">{project.summary}</p>
      <div className="my-5 rounded-xl bg-slate-950 p-4"><div className="mb-2 flex justify-between text-sm"><span className="text-slate-400">Feasibility for you</span><strong className="text-emerald-300">{feasible}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-cyan-400" style={{ width: `${feasible}%` }}/></div><p className="mt-2 text-xs text-slate-500">{form.teamSize} person team · {project.duration}</p></div>
      <p className="text-sm font-medium text-slate-300">Core features</p><ul className="mt-2 space-y-2 text-sm text-slate-400">{project.features.slice(0, 3).map(feature => <li key={feature} className="flex gap-2"><Check size={15} className="mt-0.5 shrink-0 text-indigo-400"/>{feature}</li>)}</ul><div className="mt-6 flex gap-3"><Button className="flex-1" onClick={() => navigate(`/mentor/${project.id}`)}>Build this</Button><Button variant="outline" onClick={() => save(project.id)}>{isSaved ? 'Saved' : 'Save'}</Button></div>
    </article>; })}</div></div></div>;

  return <div className="min-h-screen bg-slate-950 p-5 text-slate-100 md:flex md:items-center md:justify-center"><section className="w-full max-w-3xl rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-9">
    <div className="mb-8 flex items-center justify-between"><div><p className="text-sm font-semibold text-indigo-300">PROJECT MATCHER</p><h1 className="mt-1 text-2xl font-bold">Tell us what you want to build.</h1></div><span className="rounded-full bg-slate-800 px-3 py-1 text-sm text-slate-300">{step} / 3</span></div><div className="mb-8 flex gap-2">{[1,2,3].map(n => <div key={n} className={`h-1.5 flex-1 rounded-full ${n <= step ? 'bg-indigo-500' : 'bg-slate-800'}`}/>)}</div>
    {step === 1 && <div><label className="mb-3 block text-sm font-medium">Which area excites you most?</label><div className="grid gap-3 sm:grid-cols-2">{domains.map(domain => <button key={domain} onClick={() => setForm({...form, domain})} className={`rounded-xl border p-4 text-left transition ${form.domain === domain ? 'border-indigo-500 bg-indigo-500/15 text-white' : 'border-slate-700 bg-slate-950 text-slate-400 hover:border-slate-500'}`}><Lightbulb size={18} className="mb-2 text-indigo-300"/>{domain}</button>)}</div><Button className="mt-7 w-full" onClick={() => setStep(2)}>Continue</Button></div>}
    {step === 2 && <div className="space-y-6"><div><label className="mb-2 block text-sm font-medium">Your current skills</label><input value={form.skills} onChange={e => setForm({...form, skills: e.target.value})} placeholder="e.g. React, Python, Figma, SQL" className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white outline-none focus:border-indigo-500"/></div><div><label className="mb-2 block text-sm font-medium">Preferred challenge level</label><div className="grid grid-cols-3 gap-2">{['Beginner','Intermediate','Advanced'].map(level => <button key={level} onClick={() => setForm({...form, complexity: level})} className={`rounded-lg border p-3 text-sm ${form.complexity === level ? 'border-indigo-500 bg-indigo-500/15 text-indigo-200' : 'border-slate-700 text-slate-400'}`}>{level}</button>)}</div></div><div className="flex gap-3"><Button variant="outline" className="flex-1" onClick={() => setStep(1)}>Back</Button><Button className="flex-1" onClick={() => setStep(3)}>Continue</Button></div></div>}
    {step === 3 && <div className="space-y-6"><div><label className="mb-2 block text-sm font-medium">Time available</label><select value={form.duration} onChange={e => setForm({...form, duration: e.target.value})} className="w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white"><option>1 month</option><option>2-3 months</option><option>4-6 months</option></select></div><div><label className="mb-2 flex items-center gap-2 text-sm font-medium"><Users size={16}/> Team size</label><div className="grid grid-cols-3 gap-2">{['1','2','3+'].map(size => <button key={size} onClick={() => setForm({...form, teamSize: size})} className={`rounded-lg border p-3 text-sm ${form.teamSize === size ? 'border-indigo-500 bg-indigo-500/15 text-indigo-200' : 'border-slate-700 text-slate-400'}`}>{size} {size === '1' ? 'person' : 'people'}</button>)}</div></div><div className="flex gap-3"><Button variant="outline" className="flex-1" onClick={() => setStep(2)}>Back</Button><Button className="flex-1" onClick={generate} disabled={loading}>{loading ? 'Finding matches…' : 'Generate ideas'}</Button></div></div>}
  </section></div>;
}
